#![allow(dead_code)]

// ~~~ Generated by ChatGPT ~~~

use chrono::{DateTime, NaiveDateTime, Utc};
use serde::Deserialize;

#[derive(Debug, Deserialize)]
pub struct SyllabusLessonItem {
	pub lesson: SyllabusLesson,

	#[serde(rename = "type")]
	pub lesson_type: String,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SyllabusLesson {
	pub lesson: SyllabusLessonDetails,
	pub medias: Vec<SyllabusMedia>,
	pub user_section_role: String,
	pub capture_started_at: DateTime<Utc>,
	pub capture_ended_at: DateTime<Utc>,
	pub question_count: usize,
	pub is_scheduled: bool,
	pub has_content: bool,
	pub has_video: bool,
	pub has_video_hidden_due_to_captions: bool,
	pub has_slide_deck: bool,
	pub is_live: bool,
	pub is_interactive_media: bool,
	pub is_past: bool,
	pub is_future: bool,
	pub is_360_video: bool,
	pub is_audio_only: bool,
	pub start_time_utc: DateTime<Utc>,
	pub end_time_utc: DateTime<Utc>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SyllabusLessonDetails {
	pub id: String,
	pub institution_id: String,
	pub section_id: String,
	pub capture_occurrence_id: String,
	pub name: String,
	pub timing: SyllabusTiming,
	pub time_zone: SyllabusTimeZone,
	pub from_schedule: bool,
	pub should_stream_live: bool,
	pub created_at: DateTime<Utc>,
	pub updated_at: DateTime<Utc>,
	pub is_folder_lesson: bool,
	pub display_name: String,
	pub lesson_has_name: bool,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SyllabusTiming {
	pub start: NaiveDateTime,
	pub end: NaiveDateTime,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SyllabusTimeZone {
	pub id: String,
	pub name: String,
	pub standard_offset: String,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SyllabusMedia {
	pub id: String,
	pub media_type: String,
	pub title: String,
	pub is_available: bool,
	pub is_hidden_due_to_captions: bool,
	pub is_read: bool,
	pub is_scheduled: bool,
	pub is_processing: bool,
	pub is_failed: bool,
	pub is_preliminary: bool,
	pub is_interactive_media: bool,
	pub is_360_video: bool,
	pub is_audio_only: bool,
	pub thumbnail_uri: String,
	pub capture_occurrence_id: String,
}

pub type SyllabusRes = Vec<SyllabusLessonItem>;